FROM alpine:latest
RUN apk add --no-cache iputils-ping
CMD ["ping"]
ENTRYPOINT ["google.com"]

RUN adduser -D mkfs
USER mkfs
RUN apk add --no-cache curl
# This dictates exactly what happens when the container boots up
ENTRYPOINT ["curl", "-s", "https://ifconfig.me"]