FROM alpine:latest
RUN apk add --no-cache ping
CMD ["ping"]
ENTRYPOINT ["google.com"]

RUN useradd -m mkfs
RUN echo "mkfs:mkfs" | chpasswd
RUN apk add --no-cache curl
# This dictates exactly what happens when the container boots up
ENTRYPOINT ["curl", "-s", "https://ifconfig.me"]